Repository 0xM0na/HealthSystem, pull requests merged in 2024-12, with the labels that each got.

#29 Styling
  static/js/main.js
  static/lib/animate/animate.css
  static/lib/animate/animate.min.css
  static/lib/animate/easing/easing.js
  static/lib/animate/easing/easing.min.js
  static/lib/counterup/counterup.min.js
  static/lib/owlcarousel/LICENSE
  static/lib/owlcarousel/assets/ajax-loader.gif
  static/lib/owlcarousel/assets/owl.carousel.css
  static/lib/owlcarousel/assets/owl.carousel.min.css
  static/lib/owlcarousel/assets/owl.theme.default.css
  static/lib/owlcarousel/assets/owl.theme.default.min.css
  static/lib/owlcarousel/assets/owl.theme.green.css
  static/lib/owlcarousel/assets/owl.theme.green.min.css
  static/lib/owlcarousel/assets/owl.video.play.png
  static/lib/owlcarousel/owl.carousel.js
  static/lib/owlcarousel/owl.carousel.min.js
  static/lib/tempusdominus/css/tempusdominus-bootstrap-4.css
  static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css
  static/lib/tempusdominus/js/moment-timezone.min.js
  static/lib/tempusdominus/js/moment.min.js
  static/lib/tempusdominus/js/tempusdominus-bootstrap-4.js
  static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js
  static/lib/waypoints/links.php
  static/lib/waypoints/waypoints.min.js
  static/lib/wow/wow.js
  static/lib/wow/wow.min.js
Labels: enhancement

#31 appoitment
  templates/appointment.html
Labels: feature

#36 header-footer of user pg
  templates/userincludes/footer.html
  templates/userincludes/header.html
Labels: enhancement

#63 Add data.sql file
  data.sql
Labels: sprint 6
